---
###########################################
# The rules used for linting Dockerfile files
# https://github.com/github/super-linter/blob/main/TEMPLATES/.hadolint.yaml
# https://github.com/hadolint/hadolint
###########################################

failure-threshold: error

ignored: