version: "3.9"
services:
  cpedevcontainer:
    container_name: cpedevcontainer
    hostname: cpedevcontainer
    image: northamerica-northeast1-docker.pkg.dev/tools-369802/management/cpedevcontainer:${TAG}
    secrets:
      - source: pub_cert1
        target: /usr/local/share/ca-certificates/pub_cert1.crt
      - source: pub_cert2
        target: /usr/local/share/ca-certificates/pub_cert2.crt
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # - type: volume
      #   source: vol
      #   target: /home/${CPE_USERNAME}/
secrets:
  pub_cert1:
    file: ${PUB_CERT1_PATH}
  pub_cert2:
    file: ${PUB_CERT2_PATH}
volumes:
  vol:
