version: "3.7"
services:
  cpedevcontainer:
    container_name: cpedevcontainer
    hostname: cpedevcontainer
    image: northamerica-northeast1-docker.pkg.dev/tools-369802/management/cpedevcontainer:${TAG}
    build:
      shm_size: '2gb'
      labels:
        ca.gc.ssc-spc.ctob.author: "Cloud Platform Engineering"
        ca.gc.ssc-spc.ctob.purpose: "Container used with versioned developer tools"
      network: host
    volumes:
       - type: bind
         source: /var/run/docker.sock
         target: /var/run/docker.sock
       - type: volume
         source: vol
         target: /home/${CPE_USERNAME}/
volumes:
  vol: