# A pipeline to validate proper hydration of YAML config files

# a "Build Validation Policy" (PR trigger) must be created
trigger: none

pool:
  vmImage: ubuntu-22.04

jobs:
  - job: validate_yaml
    steps:
      - checkout: self
        persistCredentials: true

      - script: |
          echo "Checking out git submodule with 'bash modupdate.sh' ..."
          bash modupdate.sh
        displayName: 'Checkout git submodule'

      - script: |
          echo "Running 'bash tools/scripts/cicd/validate-yaml.sh' ..."
          bash tools/scripts/cicd/validate-yaml.sh
        displayName: 'Validate YAML'
        env:
          ENABLE_PUSH_ON_DIFF: true
