# A pipeline to increment version tags for a git repo containing distinct packages

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-22.04

jobs:
- job: version_tagging
  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      echo "Checking out branch: $BUILD_SOURCEBRANCHNAME ."
      # using unshallow to avoid getting only the latest commit
      git fetch --unshallow
      git checkout $BUILD_SOURCEBRANCHNAME
    displayName: 'Checkout branch'

  - script: |
      echo "Checking out git submodule with 'bash modupdate.sh' ..."
      bash modupdate.sh
    displayName: 'Checkout git submodule'

  - script: |
      echo "Running 'bash tools/scripts/cicd/version-tagging.sh' ..."
      bash tools/scripts/cicd/version-tagging.sh
    displayName: 'Generate repository tags per packages'