# A pipeline to increment version tags for a git repo containing distinct packages

# permissions:
# the build service account associated with this pipeline requires:
# - read
# - contribute
# - create tag

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-22.04

jobs:
  - job: version_tagging
    steps:
      - checkout: self
        persistCredentials: true

      - script: |
          echo "Checking out git submodule with 'bash modupdate.sh' ..."
          bash modupdate.sh
        displayName: 'Checkout git submodule'

      - script: |
          echo "Running 'bash tools/scripts/cicd/version-tagging.sh' ..."
          bash tools/scripts/cicd/version-tagging.sh
        displayName: 'Generate repository tags per packages'
