# A pipeline to validate proper hydration of YAML config files
name: validate-yaml

# Triggers the workflow on pull request events but only for the "main" branch
on:
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "validate-yaml"
  validate-yaml:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Checkout git submodule
        run: |
          echo "Checking out git submodule with 'bash modupdate.sh' ..."
          bash modupdate.sh

      - name: Validate YAML
        run: |
          echo "Running 'bash tools/scripts/cicd/validate-yaml.sh' ..."
          bash tools/scripts/cicd/validate-yaml.sh
