---
#################################
## Super Linter GitHub Actions
## https://github.com/github/super-linter
#################################

name: Lint Code Base

# only run during PRs or manually
on:
  # push:
  #   branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: shellcheck command line
        if: ${{ success() || failure() }}
        run: |
          for sh_file in $(git diff origin/main --name-only -- '*.sh')
          do
            echo -e "\n##############################\n## Checking '${sh_file}' \n##############################"
            shellcheck --color --format=json1 ${sh_file}
          done

      ################################
      # Run Linter against code base
      # each step will run even if one fails
      # this is accomplished with the 'if: ${{ success() || failure() }}'
      ################################
      - name: Lint YAML
        if: ${{ success() || failure() }}
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .github/linter-rules
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yaml-lint-config.yaml

      # no linter-rules file for bash, use SHELLCHECK_OPTS to ignore certain errors and/or add command options
      # https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md
      # TODO: possibly change severity to its default 'style' and refactor as required
      - name: Lint Bash
        if: ${{ success() || failure() }}
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          VALIDATE_BASH: true
          SHELLCHECK_OPTS: "--severity=error"

      - name: Lint Docker
        if: ${{ success() || failure() }}
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .github/linter-rules
          VALIDATE_DOCKERFILE_HADOLINT: true
          DOCKERFILE_HADOLINT_FILE_NAME: .docker-hadolint-config.yaml

      - name: Lint Markdown
        if: ${{ success() || failure() }}
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .github/linter-rules
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: .markdown-lint-config.yaml
